### PR TITLE
58 update legends page style

### PR DESCRIPTION
**Pull request by sgnl**
The idea is that we could list projects, completed during dev league( and after?), below the testimonial blurb. And more?

My work, currently looks like this:

image

### CODE REVIEW

**Comment by sgnl** [comment]
I obviously display small round circle images. I see it everywhere for testimonial sites and they feel super sterile. Trying to find a blend between functional and "what everyone is used to".

**Comment by jaywon** [comment]
I love the idea of links for projects, etc... This also highlights the person and their experience at DevLeague as well as showing off their work. Great. Also BAAS :ok_hand:

**Comment by sgnl** [comment]
currently looks like this:

image

**Comment by sgnl** [comment]
Going to need to fill out the content for the People collection via Airship CMS side.

**Comment by jaywon** [comment]
@sgnl Merged, looks good. What about when there's 100 legends? Can cross that bridge when we get there but worried about page latency or maybe we just deal. Probably best optimized for blurry image perf optimization if possible?

**Pull request merged**
