### PR TITLE
126 nav bar bugs

### PR DESCRIPTION
**Pull request by JoeKarlsson**
Fixed Nav bar, made it look pretty, and made the mobile side bar sexy as hell :dancing_men:

### CODE REVIEW

**Comment by senakamura** [comment]
The header div can use some height expansion and increased size of the hamburger icon for the mobile experience. 

Menu is much more comfy. Looks good to me so far! Just increase the header size please!

**Comment by JoeKarlsson** [comment]
@senakamura Says I should make the hamburger buttons larger - i agree with him. Hang on - I'll make the change

**Comment by JoeKarlsson** [comment]
devleague join the movement learn to code in hawaii 1


devleague join the movement learn to code in hawaii 2

**Comment by JoeKarlsson** [comment]
Made the mobile side bar links bigger

devleague join the movement learn to code in hawaii 3

**Comment by senakamura** [comment]
image

Window width `990px` to `1024px` loses both desktop and mobile menu actions.

**Comment by JoeKarlsson** [comment]
Sean fixed mobile break point issues - and I made the side bar more comfy

**Comment by senakamura** [comment]
✅  LGTM - Tested!

**Pull request merged**
