### PR TITLE
resolves #194

### LINKED ISSUE #194: tracks have incorrect deeplink URL form will not work properly
image

### PR DESCRIPTION
**Pull request by sgnl**
- apply now links using proper value for href; deeplinking now works
- added new "upcoming courses" section on tracks

new section looks like this:

image

image

### CODE REVIEW

**Comment by sgnl** [comment]
oh, and the deep-link is corrent and looks like:

image

**Comment by sgnl** [comment]
@jaywon I have an idea, what do you think about making the second "apply now" button on the page be an HTML anchor referencing the "upcoming courses" section on the same page.

re: horizontal cards

The width is smaller on these track pages. Okay with the row wrapping to a new line?

**Comment by sgnl** [comment]
🚧 Updated PR with this:

screenshot-localhost-3000-2017-03-31-15-03-20

**Comment by sgnl** [comment]
🚧 PR updated, looks like this:

screenshot-localhost-3000-2017-03-31-16-28-09

**Comment by jaywon** [comment]
@sgnl Looks great other than one outstanding task. The apply link on top, just take them straight to the application and they can select their dates their. The goal is to drive to that form and adding an additional click to get them there is a wasted click. If you can update that we good to go!

**Comment by sgnl** [comment]
I agree. Updated PR! @jaywon

**Comment by jaywon** [comment]
@sgnl Looks like something is off, but not sure what? Can you verify something wasn't missed in commit?

wut

**Comment by jaywon** [comment]
Also, can we get the sections looking more like "cards" rather than just separated sections of content?

**Comment by sgnl** [comment]
@jaywon Yeah they should look like the cards from the front page. Looks like I lost work, shouldn't take me long to get it updated.

**Pull request merged**
