### PR TITLE
Updates style career page

### PR DESCRIPTION
**Pull request by sgnl**
Adds some HTML and CSS to the page!

### CODE REVIEW

**Comment by sgnl** [comment]
I'm incorrect, this is referencing issue #50

**Comment by jaywon** [comment]
@sgnl can fix PR?

**Comment by sgnl** [comment]
Title, Body, and Apply button are the fields I think we should have. Covers everything

**Comment by sgnl** [comment]
Waiting on #60 which has the code for the email-reveal functionality.

**Comment by sgnl** [comment]
I made a Default Job Example in the Jobs collection on AirshipCMS. Here what a job listing could look like:

image

**Comment by sgnl** [comment]
Table of Contents look like this:

image

**Comment by jaywon** [comment]
LGTM :white_check_mark:

**Pull request merged**
