### PR TITLE
💄 removes snapchat social media icon from footer

### PR DESCRIPTION
**Pull request by sgnl**
works towards #134

### CODE REVIEW

**Comment by sgnl** [comment]
Added snapchat baaaack

**Comment by JoeKarlsson** [comment]
We should add `target="_blank"` to all of the social links so they don't navigate away from the DL website.

**Comment by JoeKarlsson** [comment]
Otherwise - the snap link works fine.

**Comment by sgnl** [comment]
Added `target="_blank"` to both footer's social media section and legend's page's social links

**Comment by JoeKarlsson** [comment]
LGTM! :white_check_mark:

**Pull request merged**
