### PR TITLE
#97 Homepage update

### PR DESCRIPTION
**Pull request by JoeKarlsson**
This PR resolves issues #97. This PR updates the styles to match Kelli's styles.

### CODE REVIEW

**Comment by sgnl** [comment]
path for deep linking into application form:

`GET https://application.devleague.com/enroll/:permalink`

Where permalink is a track that has a permalink, e.g. http://devleague.airshipcms.io/api/aerostat_collection/upcoming-courses

image

**Comment by JoeKarlsson** [comment]
Updated the styles and logos with Kelli's new style guide and icon pack

I still need to talk to Ray to figure out how to deep link and how to use it.

**Comment by sgnl** [comment]
@JoeKarlsson I'm gonna create a new issue for the deep linking so that I can merge this work on

**Comment by sgnl** [comment]
created issue #105

**Comment by JoeKarlsson** [comment]
Screenshot of the homepage in it's current state

devleague join the movement learn to code in hawaii

**Comment by sgnl** [comment]
✅ LGTM I'll pull this first and take care of the merge with the tracks branch. Thanks @JoeKarlsson

**Comment by sgnl** [comment]
fireshot capture 2 - devleague i join the movement learn to code in hawai_ - http___localhost_3001_

**Pull request merged**
