### PR TITLE
#43 Updated styles on all news page and show news story page

### PR DESCRIPTION
**Pull request by JoeKarlsson**
Broke up style for the news page and the news story page and updated styles so that it looks hella clean.

### CODE REVIEW

**Comment by JoeKarlsson1** [comment]
references #42

**Comment by JoeKarlsson1** [comment]
Added a link to the news story on the title and the image.

**Comment by sgnl** [comment]
Added a new field to the news posts in AirshipCMS:

`short_description`: Text type. This text field should have a short description of the articles content.

**Comment by sgnl** [comment]
**CAVEAT**: If there are three or fewer news articles, the footer will appear just "short" of the bottom of the page on mobile devices.

**Comment by JoeKarlsson** [comment]
I am going to take care of this.

**Comment by jaywon** [comment]
@JoeKarlsson any update on this?

**Comment by JoeKarlsson** [comment]
I think I fixed up the changes and made the styling consistent with the rest of the site. Resubmitting PR for review.

**Comment by jaywon** [comment]
:white_check_mark: LGTM

**Pull request merged**
